name = "JuMPGurobiExample"
uuid = "cc671b02-39b7-4349-938c-7c949dc0f4a2"
authors = ["Ben Criger <bcriger@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
